### ISSUE TITLE
PCL 1.8 generated PCD files (PointXYZRGB format) does not show the colors

### ISSUE THREAD

**Issue by nikkadim** [cloudcompare/trunk#427]
PCD files generated with PCL 1.8  in PointXYZRGB format does not show colors (all black) in CloudCompare. PCD files saved with PCL 1.6.0 shows right in CloudCompare.

PCD file from PCL 1.6.0
======================================
```
# .PCD v0.7 - Point Cloud Data file format
VERSION 0.7
FIELDS x y z rgb
SIZE 4 4 4 4
TYPE F F F F
COUNT 1 1 1 1
WIDTH 1942464
HEIGHT 1
VIEWPOINT 0 0 0 1 0 0 0
POINTS 1942464
DATA ascii
[...]
66.873619 -91.371956 773.60254 9.8649324e-039
66.99012 -91.368729 773.57526 9.7727368e-039
67.108971 -91.368729 773.57526 9.5883455e-039
67.227821 -91.368729 773.57526 9.4961499e-039
67.349045 -91.371956 773.60254 9.5883455e-039
67.470276 -91.375175 773.62976 9.4961499e-039
67.589142 -91.375175 773.62976 9.4961499e-039
67.715157 -91.384834 773.71161 9.4961499e-039
[...]
```
======================================

PCD file from PCL 1.8.0
======================================
```
# .PCD v0.7 - Point Cloud Data file format
VERSION 0.7
FIELDS x y z rgb
SIZE 4 4 4 4
TYPE F F F U
COUNT 1 1 1 1
WIDTH 1942464
HEIGHT 1
VIEWPOINT 0 0 0 1 0 0 0
POINTS 1942464
DATA ascii
[...]
66.873619 -91.371956 773.60254 7039851
66.99012 -91.368729 773.57526 6974058
67.108971 -91.368729 773.57526 6842472
67.227821 -91.368729 773.57526 6776679
67.349045 -91.371956 773.60254 6842472
67.470276 -91.375175 773.62976 6776679
67.589142 -91.375175 773.62976 6776679
67.715157 -91.384834 773.71161 6776679
[...]
```

To unpack the data into separate values, according http://docs.pointclouds.org/trunk/structpcl_1_1_point_x_y_z_r_g_b.html use:
```
PointXYZRGB p;
// unpack rgb into r/g/b
uint32_t rgb = *reinterpret_cast<int*>(&p.rgb);
uint8_t r = (rgb >> 16) & 0x0000ff;
uint8_t g = (rgb >> 8)  & 0x0000ff;
uint8_t b = (rgb)       & 0x0000ff;
```
so for 7039851 should be 107,107,107 bit not 0,0,0

**Comment by cloudcompare** [comment]
In the (Windows) binary version of CC we use PCL 1.7. Therefore it's indeed possible that it doesn't support PCL 1.8 files...

Have you tried to compile CC with PCL 1.8?

**Comment by luca-penasa** [comment]
here (http://docs.pointclouds.org/trunk/classpcl_1_1_p_c_d_writer.html) they say:
```

**Comment by luca-penasa** [comment]
here (http://docs.pointclouds.org/trunk/classpcl_1_1_p_c_d_writer.html) they say:

Caution: PointCloud structures containing an RGB field have traditionally used packed float values to store RGB data. Storing a float as ASCII can introduce variations to the smallest bits, and thus significantly alter the data. This is a known issue, and the fix involves switching RGB data to be stored as a packed integer in future versions of PCL.

So it looks like they finally made it. Compiling with 1.8 should solve the issue I think . They should have introduced some kind of non-compatibility maybe you could notify this problem to them (?)

**Comment by nikkadim** [comment]
I'll try to compile from trunk with PCL1.8, will let you know.

**Comment by nikkadim** [comment]
Can't compile with PCL 1.8 (MSVC2010 x64), lot of  "error C2216: 'override' cannot be used with 'inline'".

**Comment by cloudcompare** [comment]
'override' is a C++x11 keyword. You'll need Visual 2013 or newer to compile PCL 1.8 (and it's the same for CloudCompare by the way)

**Comment by nikkadim** [comment]
Hm, I have no problem to compile PCL 1.8 with MSVC2010, it's only appears in CC.

**Comment by cloudcompare** [comment]
Oh I thought the issue was with PCL 1.8. But as I said, CC does need Visual 2013 or newer.

**Comment by nikkadim** [comment]
Thank you, what option should I enable to be compile CC with PCL? By default it's compiled without PCD-format support. Thank you.

**Comment by nikkadim** [comment]
What options should I enable to compile CC with ability to load PCD files? qPCL plugin is not enough?

**Comment by cloudcompare** [comment]
You "simply" have to compile the qPLC plugin (see the INSTALL_QPCL_PLUGIN option in CMake). It will in fact add two plugins, one for importing some PCL functions, the other is an "I/O" plugin that allows CC to load PCD files.

**Comment by nikkadim** [comment]
Hm, I did that. And I have two DLL after install: QPCL_IO_PLUGIN.dll and QPCL_PLUGIN.dll in plugins subfolder. And can see PCL in Pluging menu (PCL Wraper... ) in CloudCompare but can't open PCL files. Any ideas?

**Comment by cloudcompare** [comment]
The wrapper is the other plugin. 
If you are on Windows make sure PCL DLLs are in the CloudCompare folder.

**Comment by nikkadim** [comment]
I've used default installer, so I have all DLL's including PCL dll's in CC folder (c:\Program Files\CloudCompareProjects\CloudCompare\)

Here is startup log in console:
`[15:31:20] [Global Shift] Max abs. coord = 1e+04 / max abs. diag = 1e+06
[15:31:20] [ccColorScalesManager] Found 0 custom scale(s) in persistent settings
[15:31:20] [Plugins] Plugin lookup dirs: C:/Program Files/CloudCompareProjects/CloudCompare/plugins
[15:31:20] Found plugin: CSV Matrix I/O filter (QCSV_MATRIX_IO_PLUGIN.dll)
[15:31:20] Found plugin: E.D.L. (shader) (QEDL_PLUGIN.dll)
[15:31:20] [Plugin] File 'QPCL_IO_PLUGIN.dll' doesn't seem to be a valid plugin	(Cannot load library C:/Program Files/CloudCompareProjects/CloudCompare/plugins/QPCL_IO_PLUGIN.dll: The specified module could not be found.)
[15:31:20] Found plugin: PCL wrapper (QPCL_PLUGIN.dll)
[15:31:20] Found plugin: P.C.V. (Ambient Occlusion) (QPCV_PLUGIN.dll)
[15:31:20] [Plugin][CSV Matrix I/O filter] New file extension(s) registered: CSV
[15:31:20] [ccGLWindow] Perspective is on by default (object-centered)
[15:31:20] CloudCompare started!
[15:31:20] [3D View 1] Graphics card manufacturer: NVIDIA Corporation
[15:31:20] [3D View 1] Renderer: GeForce GTX 470/PCIe/SSE2
[15:31:20] [3D View 1] GL version: 4.5.0 NVIDIA 353.90
[15:31:20] [3D View 1] GLSL Version: 4.50 NVIDIA
[15:31:20] [3D View 1] VBOs available
[15:31:20] [3D View 1] Shaders available
[15:31:20] [3D View 1] GL filters available
[15:31:20] [3D View 1] Color ramp shader loaded successfully
[15:31:20] [3D View 1] Stereo mode: not supported
[15:31:20] [ccGLWindow] 3D view initialized
[15:31:20] [Global Shift] Max abs. coord = 1e+04 / max abs. diag = 1e+06`

**Comment by cloudcompare** [comment]
> [15:31:20] [Plugin] File 'QPCL_IO_PLUGIN.dll' doesn't seem to be a valid plugin (Cannot load library C:/Program Files/CloudCompareProjects/CloudCompare/plugins/QPCL_IO_PLUGIN.dll: The specified module could not be found.)

Apparently there's a missing dependency. Maybe you could use the Dependency Walker on the plugin DLL to guess which DLLs are missing?

**Comment by nikkadim** [comment]
Thank you! It was OpenNI2.dll, not even OpenNI64.dll as DW shows.

But the initial problem still there. Now I have CC compiled with PCL 1.8 under MSVC2013, but still PointXYZRGB PCD (saved with PCL 1.8) in CC shows black instead of RGB.

**Comment by cloudcompare** [comment]
Ah!

Can you share the file with us maybe?

**Comment by nikkadim** [comment]
Sure, [http://nikkadim.com/files/d4_same.7z](url) 500KB

**Comment by cloudcompare** [comment]
I looked at what happens in debug mode:

The color field is loaded as a block when calling ```pcl::io::loadPCDFile```. Colors are stored in a 32 bits integer field named 'rgb'.

Things get messier when converting the generic input ```pcl::PCLPointCloud2``` structure (the one returned by ```pcl::io::loadPCDFile```) to a ```pcl::PointCloud<OnlyRGB>``` structure. The color field is simply ignored. Apparently the problem is that PCL 1.7 still expects a field named 'rgb' to be coded as  packed float values only (see Luca's answer). And I guess PCL 1.8 also expects this as it still fails on your side.

How did you generate this file exactly? (I mean with a color field coded as 32 bits integers but named 'rgb' instead of 'rgba').

Anyway as PCL also expects an 'rgba' field to be coded as 32 bits integers, I updated the code of the plugin to handle 'rgba' fields. But you still have to change the field description from 'rgb' to 'rgba' in your file header to load it with colors.

Alternatively you could patch PCL to accept 'rgb' fields with float packed values (see the ```FieldMatches<PointT, fields::rgb>``` structure in 'common\include\pcl\point_types.h').
